# combination of environments from pytorch and tensorflow projects from vislab
# 28 april 2022
name: null

channels:
  - conda-forge
  - defaults

dependencies:
  - biopython
  - git
  - ipython
  - matplotlib
  - numpy
  - pandas
  - pip
  - pip:
    - -r requirements.txt
  - python=3.10.4
  - scikit-learn
  - scipy

