# combination of environments from pytorch and tensorflow projects from vislab
# 28 april 2022
name: null

channels:
  - conda-forge
  - bioconda
  - pytorch

dependencies:
  - absl-py=1.0.0
  - biopython=1.79
  - chex=0.0.7
  - cudatoolkit=11.8
  - dm-haiku=0.0.10
  - dm-tree=0.1.8
  - git
  - immutabledict=2.0.0
  - ipython
  - matplotlib
  - ml-collections=0.1.0
  - numpy=1.24.3
  - openmm=7.7.0
  - pandas=2.0.3
  - pdbfixer
  - pip
  - pip:
    - -r requirements.txt
  - python=3.10
  - seaborn
  - scikit-learn
  - scipy=1.11.1
  - tensorflow=2.13
  - bioconda::hmmer==3.3.2
  - bioconda::hhsuite==3.3.0
  - bioconda::kalign2==2.04